//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class chi_tiet_san_phams : XPLiteObject
    {
        string fso_seri;
        [Key]
        [Size(20)]
        public string so_seri
        {
            get { return fso_seri; }
            set { SetPropertyValue<string>(nameof(so_seri), ref fso_seri, value); }
        }
        san_phams fid_san_pham;
        [Association(@"chi_tiet_san_phamsReferencessan_phams")]
        public san_phams id_san_pham
        {
            get { return fid_san_pham; }
            set { SetPropertyValue<san_phams>(nameof(id_san_pham), ref fid_san_pham, value); }
        }
        khuyen_mais fid_khuyen_mai;
        [Association(@"chi_tiet_san_phamsReferenceskhuyen_mais")]
        public khuyen_mais id_khuyen_mai
        {
            get { return fid_khuyen_mai; }
            set { SetPropertyValue<khuyen_mais>(nameof(id_khuyen_mai), ref fid_khuyen_mai, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        don_hangs fid_don_hang;
        [Association(@"chi_tiet_san_phamsReferencesdon_hangs")]
        public don_hangs id_don_hang
        {
            get { return fid_don_hang; }
            set { SetPropertyValue<don_hangs>(nameof(id_don_hang), ref fid_don_hang, value); }
        }
    }

}
