//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class CT_phieu_nhaps : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        phieu_nhap_khos fid_phieu_nhap;
        [Association(@"CT_phieu_nhapsReferencesphieu_nhap_khos")]
        public phieu_nhap_khos id_phieu_nhap
        {
            get { return fid_phieu_nhap; }
            set { SetPropertyValue<phieu_nhap_khos>(nameof(id_phieu_nhap), ref fid_phieu_nhap, value); }
        }
        san_phams fid_san_pham;
        [Association(@"CT_phieu_nhapsReferencessan_phams")]
        public san_phams id_san_pham
        {
            get { return fid_san_pham; }
            set { SetPropertyValue<san_phams>(nameof(id_san_pham), ref fid_san_pham, value); }
        }
        int fso_luong;
        public int so_luong
        {
            get { return fso_luong; }
            set { SetPropertyValue<int>(nameof(so_luong), ref fso_luong, value); }
        }
        decimal fdon_gia;
        public decimal don_gia
        {
            get { return fdon_gia; }
            set { SetPropertyValue<decimal>(nameof(don_gia), ref fdon_gia, value); }
        }
        decimal fthanh_tien;
        public decimal thanh_tien
        {
            get { return fthanh_tien; }
            set { SetPropertyValue<decimal>(nameof(thanh_tien), ref fthanh_tien, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
    }

}
