//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class danh_mucs : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string ften_danh_muc;
        public string ten_danh_muc
        {
            get { return ften_danh_muc; }
            set { SetPropertyValue<string>(nameof(ten_danh_muc), ref ften_danh_muc, value); }
        }
        int fid_danh_muc_cha;
        public int id_danh_muc_cha
        {
            get { return fid_danh_muc_cha; }
            set { SetPropertyValue<int>(nameof(id_danh_muc_cha), ref fid_danh_muc_cha, value); }
        }
        string flink_anh;
        [Size(255)]
        public string link_anh
        {
            get { return flink_anh; }
            set { SetPropertyValue<string>(nameof(link_anh), ref flink_anh, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"san_phamsReferencesdanh_mucs")]
        public XPCollection<san_phams> san_phamss { get { return GetCollection<san_phams>(nameof(san_phamss)); } }
    }

}
