//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class don_hangs : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        DateTime fngay;
        public DateTime ngay
        {
            get { return fngay; }
            set { SetPropertyValue<DateTime>(nameof(ngay), ref fngay, value); }
        }
        khach_hangs fid_khach_hang;
        [Association(@"don_hangsReferenceskhach_hangs")]
        public khach_hangs id_khach_hang
        {
            get { return fid_khach_hang; }
            set { SetPropertyValue<khach_hangs>(nameof(id_khach_hang), ref fid_khach_hang, value); }
        }
        don_vi_van_chuyens fid_don_vi_vc;
        [Association(@"don_hangsReferencesdon_vi_van_chuyens")]
        public don_vi_van_chuyens id_don_vi_vc
        {
            get { return fid_don_vi_vc; }
            set { SetPropertyValue<don_vi_van_chuyens>(nameof(id_don_vi_vc), ref fid_don_vi_vc, value); }
        }
        nhan_viens fid_nhan_vien;
        [Association(@"don_hangsReferencesnhan_viens")]
        public nhan_viens id_nhan_vien
        {
            get { return fid_nhan_vien; }
            set { SetPropertyValue<nhan_viens>(nameof(id_nhan_vien), ref fid_nhan_vien, value); }
        }
        decimal fthanh_tien;
        [ColumnDbDefaultValue("((1))")]
        public decimal thanh_tien
        {
            get { return fthanh_tien; }
            set { SetPropertyValue<decimal>(nameof(thanh_tien), ref fthanh_tien, value); }
        }
        int fphuong_thuc_thanh_toan;
        public int phuong_thuc_thanh_toan
        {
            get { return fphuong_thuc_thanh_toan; }
            set { SetPropertyValue<int>(nameof(phuong_thuc_thanh_toan), ref fphuong_thuc_thanh_toan, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"CT_don_hangsReferencesdon_hangs")]
        public XPCollection<CT_don_hangs> CT_don_hangss { get { return GetCollection<CT_don_hangs>(nameof(CT_don_hangss)); } }
    }

}
