//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class khuyen_mais : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string ften_khuyen_mai;
        [Size(255)]
        public string ten_khuyen_mai
        {
            get { return ften_khuyen_mai; }
            set { SetPropertyValue<string>(nameof(ten_khuyen_mai), ref ften_khuyen_mai, value); }
        }
        string flink_anh;
        [Size(255)]
        public string link_anh
        {
            get { return flink_anh; }
            set { SetPropertyValue<string>(nameof(link_anh), ref flink_anh, value); }
        }
        DateTime fngay_bat_dau;
        public DateTime ngay_bat_dau
        {
            get { return fngay_bat_dau; }
            set { SetPropertyValue<DateTime>(nameof(ngay_bat_dau), ref fngay_bat_dau, value); }
        }
        DateTime fngay_ket_thuc;
        public DateTime ngay_ket_thuc
        {
            get { return fngay_ket_thuc; }
            set { SetPropertyValue<DateTime>(nameof(ngay_ket_thuc), ref fngay_ket_thuc, value); }
        }
        string fdieu_kien_khuyen_mai;
        [Size(255)]
        public string dieu_kien_khuyen_mai
        {
            get { return fdieu_kien_khuyen_mai; }
            set { SetPropertyValue<string>(nameof(dieu_kien_khuyen_mai), ref fdieu_kien_khuyen_mai, value); }
        }
        int ftinh_trang;
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"chi_tiet_san_phamsReferenceskhuyen_mais")]
        public XPCollection<chi_tiet_san_phams> chi_tiet_san_phamss { get { return GetCollection<chi_tiet_san_phams>(nameof(chi_tiet_san_phamss)); } }
    }

}
