//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class nha_cung_caps : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string ften_ncc;
        public string ten_ncc
        {
            get { return ften_ncc; }
            set { SetPropertyValue<string>(nameof(ten_ncc), ref ften_ncc, value); }
        }
        string femail;
        public string email
        {
            get { return femail; }
            set { SetPropertyValue<string>(nameof(email), ref femail, value); }
        }
        string fso_dien_thoai;
        [Size(15)]
        public string so_dien_thoai
        {
            get { return fso_dien_thoai; }
            set { SetPropertyValue<string>(nameof(so_dien_thoai), ref fso_dien_thoai, value); }
        }
        string fdia_chi;
        [Size(255)]
        public string dia_chi
        {
            get { return fdia_chi; }
            set { SetPropertyValue<string>(nameof(dia_chi), ref fdia_chi, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"phieu_nhap_khosReferencesnha_cung_caps")]
        public XPCollection<phieu_nhap_khos> phieu_nhap_khoss { get { return GetCollection<phieu_nhap_khos>(nameof(phieu_nhap_khoss)); } }
    }

}
