//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class phieu_nhap_khos : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fma_phieu_nhap;
        [Size(20)]
        public string ma_phieu_nhap
        {
            get { return fma_phieu_nhap; }
            set { SetPropertyValue<string>(nameof(ma_phieu_nhap), ref fma_phieu_nhap, value); }
        }
        nha_cung_caps fid_nha_cung_cap;
        [Association(@"phieu_nhap_khosReferencesnha_cung_caps")]
        public nha_cung_caps id_nha_cung_cap
        {
            get { return fid_nha_cung_cap; }
            set { SetPropertyValue<nha_cung_caps>(nameof(id_nha_cung_cap), ref fid_nha_cung_cap, value); }
        }
        nhan_viens fid_nhan_vien;
        [Association(@"phieu_nhap_khosReferencesnhan_viens")]
        public nhan_viens id_nhan_vien
        {
            get { return fid_nhan_vien; }
            set { SetPropertyValue<nhan_viens>(nameof(id_nhan_vien), ref fid_nhan_vien, value); }
        }
        string fghi_chu;
        [Size(255)]
        public string ghi_chu
        {
            get { return fghi_chu; }
            set { SetPropertyValue<string>(nameof(ghi_chu), ref fghi_chu, value); }
        }
        decimal ftong_tien;
        [ColumnDbDefaultValue("((1))")]
        public decimal tong_tien
        {
            get { return ftong_tien; }
            set { SetPropertyValue<decimal>(nameof(tong_tien), ref ftong_tien, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"CT_phieu_nhapsReferencesphieu_nhap_khos")]
        public XPCollection<CT_phieu_nhaps> CT_phieu_nhapss { get { return GetCollection<CT_phieu_nhaps>(nameof(CT_phieu_nhapss)); } }
    }

}
