//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace QuanLyBanHang.Module.QuanLyBanHang
{

    public partial class san_phams : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string ften_san_pham;
        public string ten_san_pham
        {
            get { return ften_san_pham; }
            set { SetPropertyValue<string>(nameof(ten_san_pham), ref ften_san_pham, value); }
        }
        danh_mucs fid_danh_muc;
        [Association(@"san_phamsReferencesdanh_mucs")]
        public danh_mucs id_danh_muc
        {
            get { return fid_danh_muc; }
            set { SetPropertyValue<danh_mucs>(nameof(id_danh_muc), ref fid_danh_muc, value); }
        }
        int fso_luong;
        public int so_luong
        {
            get { return fso_luong; }
            set { SetPropertyValue<int>(nameof(so_luong), ref fso_luong, value); }
        }
        string flink_anh;
        [Size(255)]
        public string link_anh
        {
            get { return flink_anh; }
            set { SetPropertyValue<string>(nameof(link_anh), ref flink_anh, value); }
        }
        decimal fdon_gia;
        public decimal don_gia
        {
            get { return fdon_gia; }
            set { SetPropertyValue<decimal>(nameof(don_gia), ref fdon_gia, value); }
        }
        int fthoi_han_bao_hanh;
        public int thoi_han_bao_hanh
        {
            get { return fthoi_han_bao_hanh; }
            set { SetPropertyValue<int>(nameof(thoi_han_bao_hanh), ref fthoi_han_bao_hanh, value); }
        }
        string fdon_vi_tinh;
        [Size(20)]
        public string don_vi_tinh
        {
            get { return fdon_vi_tinh; }
            set { SetPropertyValue<string>(nameof(don_vi_tinh), ref fdon_vi_tinh, value); }
        }
        string fmo_ta;
        [Size(255)]
        public string mo_ta
        {
            get { return fmo_ta; }
            set { SetPropertyValue<string>(nameof(mo_ta), ref fmo_ta, value); }
        }
        int fid_danh_muc_cha;
        public int id_danh_muc_cha
        {
            get { return fid_danh_muc_cha; }
            set { SetPropertyValue<int>(nameof(id_danh_muc_cha), ref fid_danh_muc_cha, value); }
        }
        int ftinh_trang;
        [ColumnDbDefaultValue("((1))")]
        public int tinh_trang
        {
            get { return ftinh_trang; }
            set { SetPropertyValue<int>(nameof(tinh_trang), ref ftinh_trang, value); }
        }
        [Association(@"chi_tiet_san_phamsReferencessan_phams")]
        public XPCollection<chi_tiet_san_phams> chi_tiet_san_phamss { get { return GetCollection<chi_tiet_san_phams>(nameof(chi_tiet_san_phamss)); } }
        [Association(@"CT_don_hangsReferencessan_phams")]
        public XPCollection<CT_don_hangs> CT_don_hangss { get { return GetCollection<CT_don_hangs>(nameof(CT_don_hangss)); } }
        [Association(@"CT_phieu_nhapsReferencessan_phams")]
        public XPCollection<CT_phieu_nhaps> CT_phieu_nhapss { get { return GetCollection<CT_phieu_nhaps>(nameof(CT_phieu_nhapss)); } }
        [Association(@"CT_phieu_xuatsReferencessan_phams")]
        public XPCollection<CT_phieu_xuats> CT_phieu_xuatss { get { return GetCollection<CT_phieu_xuats>(nameof(CT_phieu_xuatss)); } }
    }

}
